version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Build"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/symphonia-wasm"
    schedule:
      interval: "weekly"
